version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"
      - "ciarams87"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"
