builds:
  - skip: true

changelog:
  skip: true

announce:
  slack:
    enabled: true
    channel: '#announcements'
    message_template: 'NGINX Plus Go Client {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'
