version: 2
builds:
  - skip: true

changelog:
  disable: true

announce:
  slack:
    enabled: true
    channel: "#announcements"
    message_template: "NGINX Plus Go Client {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}"
